<?php 
_e("General Settings","revslider"); 
_e("Position","revslider"); 
_e("Appearance","revslider"); 
_e("Navigation","revslider"); 
_e("Thumbnails","revslider"); 
_e("Mobile Visibility","revslider"); 
_e("Alternative First Slide","revslider"); 
_e("Troubleshooting","revslider"); 
_e("Delay","revslider"); 
_e("The time one slide stays on the screen in Milliseconds","revslider"); 
_e("Shuffle Mode","revslider"); 
_e("Turn Shuffle Mode on and off! Will be randomized only once at the start.","revslider"); 
_e("On","revslider"); 
_e("Off","revslider"); 
_e("Lazy Load","revslider"); 
_e("The lazy load means that the images will be loaded by demand, it speeds the loading of the slider.","revslider"); 
_e("Load Google Font","revslider"); 
_e("yes / no to load google font","revslider"); 
_e("Yes","revslider"); 
_e("No","revslider"); 
_e("Google Font","revslider"); 
_e("The google font family to load","revslider"); 
_e("To add more google fonts please read <a target=\"_blank\" href=\"http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380/faqs/15268\"> this tutorial </a> ","revslider"); 
_e("Stop Slider","revslider"); 
_e("On / Off to stop slider after some amount of loops / slides","revslider"); 
_e("Stop After Loops","revslider"); 
_e("Stop the slider after certain amount of loops. 0 related to the first loop.","revslider"); 
_e("Stop At Slide","revslider"); 
_e("Stop the slider at the given slide","revslider"); 
_e("Position on the page","revslider"); 
_e("The position of the slider on the page, (float:left, float:right, margin:0px auto;)","revslider"); 
_e("Left","revslider"); 
_e("Center","revslider"); 
_e("Right","revslider"); 
_e("Margin Top","revslider"); 
_e("The top margin of the slider wrapper div","revslider"); 
_e("px","revslider"); 
_e("Margin Bottom","revslider"); 
_e("The bottom margin of the slider wrapper div","revslider"); 
_e("Margin Left","revslider"); 
_e("The left margin of the slider wrapper div","revslider"); 
_e("Margin Right","revslider"); 
_e("The right margin of the slider wrapper div","revslider"); 
_e("Shadow Type","revslider"); 
_e("The Shadow display underneath the banner. The shadow apply to fixed and responsive modes only, the full width slider don't have a shadow.","revslider"); 
_e("No Shadow","revslider"); 
_e("1","revslider"); 
_e("2","revslider"); 
_e("3","revslider"); 
_e("Show Timer Line","revslider"); 
_e("Show the top running timer line","revslider"); 
_e("Top","revslider"); 
_e("Bottom","revslider"); 
_e("Hide","revslider"); 
_e("Background color","revslider"); 
_e("Slider wrapper div background color, for transparent slider, leave empty.","revslider"); 
_e("Padding (border)","revslider"); 
_e("The wrapper div padding, if it has value, then together with background color it it will make border around the slider.","revslider"); 
_e("Show Background Image","revslider"); 
_e("yes / no to put background image to the main slider wrapper.","revslider"); 
_e("Background Image Url","revslider"); 
_e("The background image that will be on the slider wrapper. Will be shown at slider preloading.","revslider"); 
_e("Touch Enabled","revslider"); 
_e("Enable Swipe Function on touch devices","revslider"); 
_e("Stop On Hover","revslider"); 
_e("Stop the Timer when hovering the slider","revslider"); 
_e("Navigation Type","revslider"); 
_e("Display type of the navigation bar (Default:none","revslider"); 
_e("None","revslider"); 
_e("Bullet","revslider"); 
_e("Thumb","revslider"); 
_e("Both","revslider"); 
_e("Navigation Arrows","revslider"); 
_e("Display position of the Navigation Arrows (** By navigation Type Thumb arrows always centered or none visible)","revslider"); 
_e("With Bullets","revslider"); 
_e("Solo","revslider"); 
_e("Navigation Style","revslider"); 
_e("Look of the navigation bullets  ** If you choose navbar, we recommend to choose Navigation Arrows to nexttobullets","revslider"); 
_e("Round","revslider"); 
_e("Navbar","revslider"); 
_e("Old Round","revslider"); 
_e("Old Square","revslider"); 
_e("Old Navbar","revslider"); 
_e("Always Show Navigation","revslider"); 
_e("Always show the navigation and the thumbnails.","revslider"); 
_e("Hide Navitagion After","revslider"); 
_e("Time after that the Navigation and the Thumbs will be hidden(Default: 200 ms)","revslider"); 
_e("ms","revslider"); 
_e("Navigation Horizontal Align","revslider"); 
_e("Horizontal Align of Bullets / Thumbnails","revslider"); 
_e("Navigation Vertical Align","revslider"); 
_e("Vertical Align of Bullets / Thumbnails","revslider"); 
_e("Navigation Horizontal Offset","revslider"); 
_e("Offset from current Horizontal position of Bullets / Thumbnails negative and positive direction","revslider"); 
_e("Navigation Vertical Offset","revslider"); 
_e("Offset from current Vertical  position of Bullets / Thumbnails negative and positive direction","revslider"); 
_e("Left Arrow Horizontal Align","revslider"); 
_e("Horizontal Align of left Arrow (only if arrow is not next to bullets)","revslider"); 
_e("Left Arrow Vertical Align","revslider"); 
_e("Vertical Align of left Arrow (only if arrow is not next to bullets)","revslider"); 
_e("Left Arrow Horizontal Offset","revslider"); 
_e("Offset from current Horizontal position of of left Arrow  negative and positive direction","revslider"); 
_e("Left Arrow Vertical Offset","revslider"); 
_e("Offset from current Vertical position of of left Arrow negative and positive direction","revslider"); 
_e("Right Arrow Horizontal Align","revslider"); 
_e("Horizontal Align of right Arrow (only if arrow is not next to bullets)","revslider"); 
_e("Right Arrow Vertical Align","revslider"); 
_e("Vertical Align of right Arrow (only if arrow is not next to bullets)","revslider"); 
_e("Right Arrow Horizontal Offset","revslider"); 
_e("Offset from current Horizontal position of of right Arrow negative and positive direction","revslider"); 
_e("Right Arrow Vertical Offset","revslider"); 
_e("Offset from current Vertical position of of right Arrow negative and positive direction","revslider"); 
_e("Thumb Width","revslider"); 
_e("The basic Width of one Thumbnail (only if thumb is selected)","revslider"); 
_e("Thumb Height","revslider"); 
_e("the basic Height of one Thumbnail (only if thumb is selected)","revslider"); 
_e("Thumb Amount","revslider"); 
_e("the amount of the Thumbs visible same time (only if thumb is selected)","revslider"); 
_e("Hide Slider Under Width","revslider"); 
_e("Hide the slider under some slider width. Works only in Responsive Style. Not available for Fullwidth.","revslider"); 
_e("Hide Defined Layers Under Width","revslider"); 
_e("Hide some defined layers in the layer properties under some slider width.","revslider"); 
_e("Hide All Layers Under Width","revslider"); 
_e("Hide all layers under some slider width","revslider"); 
_e("Start With Slide","revslider"); 
_e("Change it if you want to start from a different slide then 1","revslider"); 
_e("First Transition Active","revslider"); 
_e("If active, it will overwrite the first slide transition. Use it when you want a special transition for the first slide only.","revslider"); 
_e("First Transition Type","revslider"); 
_e("First slide transition type","revslider"); 
_e("Replace me!","revslider"); 
_e("First Transition Duration","revslider"); 
_e("First slide transition duration (Default:300, min: 100 max 2000)","revslider"); 
_e("First Transition Slot Amount","revslider"); 
_e("The number of slots or boxes the slide is divided into. If you use boxfade, over 7 slots can be juggy","revslider"); 
_e("JQuery No Conflict Mode","revslider"); 
_e("Turns on / off jquery noconflict mode. You can play with this option when you have some javascript conflicts.","revslider"); 
_e("Put JS Includes To Body","revslider"); 
_e("Putting the js to body (in addition to head) is good for fixing some javascript conflicts of type: TypeError: tpj('#rev_slider_1_1').show().revolution is not a function","revslider"); 
_e("True","revslider"); 
_e("False","revslider"); 
_e("Output Filters Protection","revslider"); 
_e("Activate a protection against wordpress output filters that adds html blocks to the shortcode output like P and BR","revslider"); 
_e("By Compressing Output","revslider"); 
_e("By Echo Output","revslider"); 
?>